### ISSUE TITLE
Convene governance interest group 

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#1]
Convene group of iDTF and CTSA PIs who expressed interest - goal: get feedback on governance pain points and our strawman plan.

**Comment by mellybelly** [comment]
Order of operations:
- [ ] Liz to collate participant emails
- [ ] Draft a 1 pager for emailing out (this is #29). Will be reviewed 
- [ ] Melissa and Kari to send. Email will ask for DUA examples and will include: 
- Doodle for a phone call 
- onboarding form
- place to put DUAs - suggest a form, @jmcmurry pls advise
- addition to slack and google docs

**Comment by kstephen0909** [comment]
Talked with Sean to coordinate on community calls. we will prep a googlesheet (posted in the project folder) to be used to dynamically collect a set of answers from sites about overall governance

We can talk with Jonathan Hanes, Case Western (Cleveland), and has 3 hospitals that need to share data as a potential pilot site. I have one too through a colleague connection, David Bard at OUHSC (University of Oklahoma Health Sciences Center), who also has 3 health systems that he needs to conduct data sharing with under his CTSA umbrella.

ACT PI's all in agreement that master DUA won't work, rather, we need a master DUA for each use case (i.e., cohort discovery vs. de-id observational research etc.). this is consistent with how we built DUAs for my Data QUEST network as well.

**Comment by ezampino** [comment]
Might be helpful to compile into “topics of discussion” and put on our one pager. Thoughts?

Liz

——-

________________________________

**Comment by mellybelly** [comment]
Use of an ontology would allow a single templating system to be used for different use cases. 

We should determine the strategy after the requirements are collected and other existing efforts to do similarly have been more fully evaluated.

Lets collect target sites for collection/interviews in the spreadsheet.

**Comment by kstephen0909** [comment]
We can start with the list of CTSAs in the surveys and add the one Sean mentioned and I mentioned.

Liz, can you start a googlesheet in the project drive that has a row for each of the CTSAs who checked yes on the surveys? Then we’ll add columns for a set of questions we’ll ask them to answer. I have a list started and that Sean threw together when we met. I can fill those in if you send me a link.

-k

On Mar 13, 2019, at 8:38 PM, Melissa Haendel <notifications@github.com<mailto:notifications@github.com>> wrote:


Use of an ontology would allow a single templating system to be used for different use cases.

We should determine the strategy after the requirements are collected and other existing efforts to do similarly have been more fully evaluated.

Lets collect target sites for collection/interviews in the spreadsheet.

**Comment by ezampino** [comment]
+abwilcox decided not to engage the community in this way
