### ISSUE TITLE
Governance Approaches

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#11]
Synthesize governance approaches (i.e., CTSA DUAs, ACT agreement, etc). This will require:

- [x] categorizing DUAs
- [x] marking up DUAs with key components in an iterative manner
- [ ] creating a master DUA template 
- [ ] defining the slots where DUO can be integrated
- [x] having compliance and legal experts review

**Comment by ezampino** [comment]
This correlates with the matrix we created
