### ISSUE TITLE
Add maturity model interviewees

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#2]
Include (in an ongoing fashion) maturity model interviewees. @davedorr9 @rchampieux

**Comment by mellybelly** [comment]
Assigning to Robin to coordinate a contact list from her; and/or direct obtaining of DUAs where relevant in maturity interviews.

**Comment by kstephen0909** [comment]
I have had quick correspondence with both Adam and David about this. David recommends we contact his team. We need to determine if they have a repository of interview info we can have access to.

**Comment by kstephen0909** [comment]
@mellybelly did you change the their interview template for the maturity model folks? if so, can you post a copy to our project directory so I can see what they're asking? David is under the impression that we want to change their interview guide and I was trying to reassure that we don't need to do that, but wasn't sure if that's correct.

**Comment by mellybelly** [comment]
nope, did not change a thing. I don't know if the interview guide needs changing at this time or not. Once we come up with our own questions related to governance (which I see as being much shorter list than the maturity model) we can see how they align or could be added to the current survey. We really just want to take advantage of them interviewing to potentially ask a few additional questions.

**Comment by kstephen0909** [comment]
I got the impression that any changes to their interview was majorly disruptive. Is there a survey going out or do you mean the maturity model interview guide when you say “survey?”



nope, did not change a thing. I don't know if the interview guide needs changing at this time or not. Once we come up with our own questions related to governance (which I see as being much shorter list than the maturity model) we can see how they align or could be added to the current survey. We really just want to take advantage of them interviewing to potentially ask a few additional questions.

**Comment by mellybelly** [comment]
At the end of the day, I think we just want them to ask a few questions for us. I don’t think it has to be part of the guide. (Yes I called survey).  Take a look at it - it’s informative.

Sent from my iPhone

On Mar 20, 2019, at 1:13 AM, Kari Stephens <notifications@github.com<mailto:notifications@github.com>> wrote:

I got the impression that any changes to their interview was majorly disruptive. Is there a survey going out or do you mean the maturity model interview guide when you say “survey?”
