### ISSUE TITLE
Develop sustainability plan

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#21]
How will guidance chart sustain process?

**Comment by ezampino** [comment]
[Here](https://docs.google.com/document/d/1q9tj6zza-F7U_r4RCSX03IeLnmMeJsxMcZq-Xb3GMf0/edit) is the sustainability plan. We have developed a sustainability plan for implementation with considerations in the following areas: assets, stakeholders, expansion and complexity.
