### ISSUE TITLE
Requirements from stakeholders

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#25]
We need a defined (but simple) process for obtaining requirements from stakeholders. Related to #6

**Comment by jmcmurry** [comment]
Feedback Options are:
- [ ] https://github.com/data2health/governance-pathways/issues/new
- [ ] data2health+governance@gmail.com
- [ ] slack channel #governance (onboarded participants only)

@ezampino does this look OK to you?

**Comment by kstephen0909** [comment]
I vote for slack for community based convo's and tracking. I think it's only reasonable to have more core team members (which may wind up including community based members) post issues to github. 

who receives and would respond to the gmail email address?

**Comment by ezampino** [comment]
Agreed. But getting folks to use another communication medium is like pulling teeth & they will end up emailing whomever. I wonder if we can be creative here with tools that are integrated; i.e. Github & Gmail; GitHub & Slack. Mmmm let me think about this...

Liz

——-
Kari:

I vote for slack for community based convo's and tracking. I think it's only reasonable to have more core team members (which may wind up including community based members) post issues to github.

who receives and would respond to the gmail email address?

**Comment by ezampino** [comment]
Hello, We can create a gmail account and have emails dumped into a slack channel for collective live feedback- https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack

Unfortunately we have to pay.. might be worth it though...

**Comment by kstephen0909** [comment]
potential data sharing use cases that our master agreement template(s) may address:

Enable data query tool independent activities preparatory to research (cohort   discovery)
Share row level de-identified data w/o individual IRBs and DUAs
Share limited datasets without a DUA
Share   identified datasets in a compliant way to enable the learning health system   living laboratory

**Comment by ezampino** [comment]
Consolidated into another task
