### ISSUE TITLE
repo tags - review custom tags 

### ISSUE THREAD

**Issue by cgcook** [data2health/governance-pathways#26]
@mellybelly @jmcmurry I created tags based on [this](https://docs.google.com/spreadsheets/d/1xZZ3kjJueBIXS-uvc_y7W9esV95hJfefTqJjrXglcfA/edit#gid=333483890) sheet in [this repo](https://github.com/data2health/governance-pathways) .  

Pls review and confirm this is correct and final; I will then copy over to all repos.

**Comment by jmcmurry** [comment]
Great! I think this comment belongs [here](https://github.com/data2health/operations/issues/12#issuecomment-470190723) and have moved it
