### ISSUE TITLE
Informative Community Engager - one pager 

### ISSUE THREAD

**Issue by ezampino** [data2health/governance-pathways#29]
One page document describing the mission of the project, goals and desirable outcomes. 
Address how members can contribute. 
Communication Plan for convene meetings.

**Comment by mellybelly** [comment]
see the licensing 1-pager here: https://drive.google.com/drive/folders/1Fgd5kAmjzMing9uPTRSjfbCqqGRvhHDD

**Comment by ezampino** [comment]
https://drive.google.com/drive/u/0/folders/1bxu7JRnVgZsaj8xkthsKwpZBiasgDnXL
Rough draft one pager
