### ISSUE TITLE
Schedule Weekly Project Meetings 

### ISSUE THREAD

**Issue by ezampino** [data2health/governance-pathways#31]
Attendees:
Melissa Haendel @mellybelly 
John Wilbanks @wilbanksjohn 
Liz Zampino @ezampino 
Kair Stephen @kstephen0909 
Sean Mooney @sdmooney 

Melissa added: Justin Guinney @jguinney 
Christine (?) from Sage.

**Comment by ramussa** [comment]
This meeting has been scheduled for Mondays at 10:30am-11am PST. First occurrence is on the 25th, and recurs on a weekly basis.

**Comment by ezampino** [comment]
Melissa has also requested the presence of Christine from Sage...

**Comment by ezampino** [comment]
I have asked Rania to move these to 2PT on Tuesdays in order to include John from Sage.

**Comment by ezampino** [comment]
We moved weekly meetings from 10:30-11 to 2PT on Tuesday to accommodate John and Melissa… when schedules are more open (>2 weeks away) hopefully everyone can attend regularly, but for now the core members are available. I cannot think of any other way to solve this and open to suggestions.

**Comment by ezampino** [comment]
There are set for Tuesdays 2-3PT. We invited everyone to attend at the all hands meeting on 3.22.19

**Comment by ramussa** [comment]
Can you please provide her email?

Thanks!

--Rania
