### ISSUE TITLE
Solidify use cases to be addressed in master agreement(s)

### ISSUE THREAD

**Issue by kstephen0909** [data2health/governance-pathways#32]
i.e., cohort discovery, de-id data sharing for obs studies, limited data sets, identified data sharing

**Comment by ezampino** [comment]
Closing issue this is complete: https://docs.google.com/spreadsheets/d/1f6s7iIU3KDSa_57byksNeNTqcmsVnfKROsbWoHTKv70/edit#gid=1999419187
