### ISSUE TITLE
Stakeholders

### ISSUE THREAD

**Issue by ezampino** [data2health/governance-pathways#36]
Stakeholders:
- [x] Requirements to be a 'stakeholder'
- [x] Identify stakeholders that align with matrix dimensions
- [x] Conduct outreach to individuals/orgs (identify recruitment process)

- [x] Identify roles: Approvers, creators, & moderators

- [x] Identify matrix reviewers (quality check) [Associated with Task](https://github.com/data2health/governance-pathways/issues/39)

**Comment by jmcmurry** [comment]
@ezampino Please link to where these stakeholders and their above metadata are documented.
