### ISSUE TITLE
Draft email to CTSA hubs

### ISSUE THREAD

**Issue by ezampino** [data2health/governance-pathways#37]
Email requesting DUA that can be mapped to the matrix

**Comment by ezampino** [comment]
We did this and didn't get responses; therefore we started to do an online search of publicly available DUAs (see 
"public tab" https://docs.google.com/spreadsheets/d/1N2WCIchUXc8xbNsYueVOGuMir_eH0MufCOrJxcq1gbg/edit#gid=1536467670

**Comment by jmcmurry** [comment]
Have you followed up with Merce Crosas & Diane Keogh at Harvard? They're not on your list of [given to us](https://docs.google.com/spreadsheets/d/1N2WCIchUXc8xbNsYueVOGuMir_eH0MufCOrJxcq1gbg/edit#gid=0) however they were keen to collaborate.

**Comment by ezampino** [comment]
Yes, we have several times.. I have asked Melissa to step in and bug them for us. thanks
