### ISSUE TITLE
Matrix Requirements

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#5]
For example: 

- Enable data query tool independent activities preparatory to research (cohort discovery)
- Share row level de-identified data w/o an IRB and DUA
- Share limited datasets without a DUA
- Share identified datasets in a compliant way to enable the learning health system living laboratory
- Better understanding of when a membership agreement, a study specific DUA, a master DUA w/o a BAA and when a master DUA with a BAA is required

**Comment by ezampino** [comment]
These examples can be found in the matrix doc compiled https://docs.google.com/document/d/1g5hbbEPO6bqtbiMppjtYTZ_qb5IDNC-SUmUgtPM50kc/edit
