### ISSUE TITLE
Collect requirements from experts

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#6]
This group may be external to CTSA hubs.

**Comment by kstephen0909** [comment]
I see the task. Traveling yesterday and today at ASU. Melissa, do you have time tomorrow to meet and coordinate? I don’t think we set up our next meeting.

**Comment by jmcmurry** [comment]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by jmcmurry** [comment]
ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.

**Comment by ezampino** [comment]
Related to: https://github.com/data2health/governance-pathways/issues/35

**Comment by ezampino** [comment]
Closing task- due to reorg of this project
