### ISSUE TITLE
Review other sources for potential requirements

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#7]
For example: DUOS, Elixr, European agreement, NIH DUA policies, ACT agreement, PCORnet CDRNs, TriNetX, etc.

**Comment by kstephen0909** [comment]
DUOS, Elixr, European agreement (Ken - clinical trial data sharing), NIH DUA policies, ACT agreement, PCORnet CDRNs, TriNetX, CTSA Hub DUAs
