### ISSUE TITLE
Collect DUAs across CTSA consortium

### ISSUE THREAD

**Issue by mellybelly** [data2health/governance-pathways#8]
These will be collected via specific interactions or via Maturity Model interviews/contacts. @rchampieux @davedorr9

**Comment by ezampino** [comment]
Please put DUA in this folder: https://drive.google.com/drive/u/0/folders/11_ROQq1Na6_a669DU937tJYNebtOzNdu

**Comment by kstephen0909** [comment]
@ezampino let's make sure the agenda for community meetings in April include collection of master agreements (including DUAs folks may have). we can include this in the email invite as well.

**Comment by ezampino** [comment]
In correlation with issue # [40](https://github.com/data2health/governance-pathways/issues/40)

**Comment by ezampino** [comment]
We reached out the the CTSA community and did not received any DUAs
